// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/3/2026, 9:51:04 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/user/Downloads/medchart-opd/medchart/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Downloads/medchart-opd/medchart/components/consultation/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Downloads/medchart-opd/medchart/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Downloads/medchart-opd/medchart/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Downloads/medchart-opd/medchart/plugins/**/*.{js,ts,mjs}","C:/Users/user/Downloads/medchart-opd/medchart/composables/**/*.{js,ts,mjs}","C:/Users/user/Downloads/medchart-opd/medchart/utils/**/*.{js,ts,mjs}","C:/Users/user/Downloads/medchart-opd/medchart/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Downloads/medchart-opd/medchart/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Downloads/medchart-opd/medchart/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Downloads/medchart-opd/medchart/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;